test commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,7 +2,8 @@
 
 # Extract staged files to a temp directory
 export NODE_MODULES=$(npm run -s pre-lint)
-export ESLINT_PATH=`echo $NODE_MODULES"/eslint/bin/eslint.js"`
+export ESLINT_PATH=`echo $NODE_MODULES"/eslint/bin/eslint.js -c .eslintrc"`
+export STYLELINT_PATH=`echo $NODE_MODULES"/eslint/bin/eslint.js -c .eslintrc"`
 JSFILES=$(git diff-index --name-status --cached HEAD | grep -v ^D | egrep '.js$' | cut -c3-)
 CSSFILES=$(git diff-index --name-status --cached HEAD | grep -v ^D | egrep '.scss$' | cut -c3-)
 
@@ -11,6 +12,7 @@ if [ "$JSFILES" == "" ]; then
 fi
 
 PASS=true
+CSSPASS=true
 for FILE in $JSFILES
 do
   $ESLINT_PATH "$FILE" > /dev/null
@@ -28,8 +30,32 @@ do
     PASS=false
   fi
 done
+for FILE in $CSSFILES
+do
+  $ESLINT_PATH "$FILE" > /dev/null
+
+  if [ $? -eq 0 ]; then
+    printf "\t\033[32mESLint Passed: $FILE\033[0m\n"
+  else
+    printf "\t\033[41mESLint Failed: $FILE\033[0m\n"
+    $STYLELINT_PATH "$FILE" --fix
+
+    if [ $? -eq 0 ]; then
+      printf "\n \n There were errors, but they were all able to be \033[42mautomatically fixed\033[0m by eslint. Please stage those fixes and commit again. \n \n"
+    fi
+
+    CSSPASS=false
+  fi
+done
 
 if ! $PASS; then
+  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  exit 1
+else
+  printf "\033[42mESLINT SUCCEEDED\033[0m\n"
+fi
+
+if ! $CSSPASS; then
   printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
   exit 1
 else
